[package]
name = "reflex-core"
version = "0.1.0"
edition = "2024"

[dependencies]
enum-as-inner = "0.6.1"
mio = { version = "1.0.4", features = ["os-poll", "net"] }
petgraph = "0.8.2"
slab = "0.4.11"
time = "0.3.42"
